CREATE TABLE IF NOT EXISTS formulario_tabla_matriz (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo_formulario TEXT NOT NULL UNIQUE,
  nombre_formulario TEXT NOT NULL,
  tabla_principal TEXT NOT NULL,
  modulo TEXT NOT NULL,
  requisito_codigo TEXT NOT NULL,
  etapa_phva phva_etapa NOT NULL,
  campos JSONB NOT NULL DEFAULT '[]'::jsonb,
  tablas_relacionadas JSONB NOT NULL DEFAULT '[]'::jsonb,
  evidencia_generada TEXT NOT NULL,
  accion_agente TEXT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

WITH matrix(codigo_formulario, nombre_formulario, tabla_principal, modulo, requisito_codigo, etapa_phva, campos, tablas_relacionadas, evidencia_generada, accion_agente) AS (
VALUES
  ('FORM-ORGANIZACIONES', 'Organizaciones', 'organizaciones', 'empresa', '4.1', 'planear', '["id", "nombre", "nit", "direccion", "correo_contacto", "fecha_creacion"]', '["usuarios", "sistemas_gestion", "personas", "documentos", "evidencias"]', 'Registro diligenciado de Organizaciones', 'Preparar contexto, alcance y datos base de la organizacion.'),
  ('FORM-USUARIOS', 'Usuarios', 'usuarios', 'usuarios', '5.3', 'planear', '["id", "nombre", "correo", "contrasena_hash", "rol", "id_organizacion"]', '["organizaciones", "usuario_roles", "acciones_gestion", "evidencias"]', 'Registro diligenciado de Usuarios', 'Asignar responsables y validar roles del sistema.'),
  ('FORM-CAPITULOS-ISO', 'Capitulos Iso', 'capitulos_iso', 'norma', '4.4', 'planear', '["id", "codigo", "titulo"]', '["normas", "norma_versiones", "requisitos_normativos"]', 'Registro diligenciado de Capitulos Iso', 'Conectar registros con requisitos normativos y PHVA.'),
  ('FORM-COMPROMISO-LIDERAZGO', 'Compromiso Liderazgo', 'compromiso_liderazgo', 'liderazgo', '5.1', 'planear', '["id", "id_organizacion", "id_usuario", "nombre_empresa", "nit", "nombre_representante", "cargo_representante", "fecha_firma", "firma_imagen_url", "archivo_adjunto", "fecha_creacion", "fecha_actualizacion", "estado"]', '["organizaciones", "usuarios", "evidencias", "acciones_gestion"]', 'Registro diligenciado de Compromiso Liderazgo', 'Preparar borradores para aprobacion de la direccion.'),
  ('FORM-CONTEXTO-INTERNO-EXTERNO', 'Contexto Interno Externo', 'contexto_interno_externo', 'planificacion', '4.1', 'planear', '["id", "id_organizacion", "id_usuario", "alcance", "contexto_social_cultural", "contexto_politico_legal", "contexto_economico", "contexto_geografico_ambiental", "tendencias", "partes_interesadas", "vision", "mision", "valores", "organigrama", "objetivos", "politica", "cultura", "capacidades_personal", "equipos_utilizados", "procesos", "sistemas_informacion", "relaciones_contratuales", "objetivos_gestion_riesgo", "relacion_sgsst", "metodologias_riesgo", "archivo_adjunto", "fecha_creacion", "fecha_actualizacion", "estado"]', '["organizaciones", "usuarios", "evidencias"]', 'Registro diligenciado de Contexto Interno Externo', 'Detectar brechas de contexto, alcance y partes interesadas.'),
  ('FORM-CONTEXTO-ACTIVIDADES', 'Contexto Actividades', 'contexto_actividades', 'actividades', '4.3', 'planear', '["id", "id_organizacion", "nombre_actividad", "descripcion", "fecha_inicio", "fecha_fin", "riesgo_asociado", "estado", "fecha_creacion"]', '["organizaciones", "actividades_servicios", "riesgos"]', 'Registro diligenciado de Contexto Actividades', 'Cruzar actividad, personal, equipos, riesgos y participantes.'),
  ('FORM-IMPACTO-RIESGO', 'Impacto Riesgo', 'impacto_riesgo', 'riesgos', '6.1.2', 'planear', '["valor", "categoria", "descripcion"]', '["mapa_riesgos", "riesgos"]', 'Registro diligenciado de Impacto Riesgo', 'Calcular brechas y proponer acciones preventivas.'),
  ('FORM-PROBABILIDAD-RIESGO', 'Probabilidad Riesgo', 'probabilidad_riesgo', 'riesgos', '6.1.2', 'planear', '["valor", "categoria", "descripcion"]', '["mapa_riesgos", "riesgos"]', 'Registro diligenciado de Probabilidad Riesgo', 'Calcular brechas y proponer acciones preventivas.'),
  ('FORM-MAPA-RIESGOS', 'Mapa Riesgos', 'mapa_riesgos', 'riesgos', '6.1.2', 'planear', '["id", "id_organizacion", "id_usuario", "actividad", "peligro", "riesgo", "consecuencia", "impacto_inicial", "probabilidad_inicial", "nivel_riesgo_inicial", "control_accion", "impacto_residual", "probabilidad_residual", "nivel_riesgo_residual", "responsable_control", "estado_control", "fecha_creacion", "fecha_actualizacion"]', '["sistemas_gestion", "actividades_servicios", "usuarios", "acciones_gestion", "evidencias"]', 'Registro diligenciado de Mapa Riesgos', 'Calcular brechas y proponer acciones preventivas.'),
  ('FORM-PLANTILLAS-DOCUMENTOS', 'Plantillas Documentos', 'plantillas_documentos', 'documentos', '7.5', 'hacer', '["id", "codigo", "titulo", "tipo", "contenido", "aplicacion", "fecha_creacion"]', '["documentos", "documento_versiones"]', 'Registro diligenciado de Plantillas Documentos', 'Generar borradores, controlar versiones y asociar evidencias.'),
  ('FORM-PROCEDIMIENTOS-SGS', 'Procedimientos Sgs', 'procedimientos_sgs', 'documentos', '4.4', 'planear', '["id", "id_organizacion", "titulo", "codigo", "numeral_iso", "contenido", "archivo_adj", "responsable", "version", "fecha_aprobacion", "estado", "proxima_accion", "fecha_proxima_accion", "fecha_creacion"]', '["organizaciones", "documentos", "procedimientos_implementados"]', 'Registro diligenciado de Procedimientos Sgs', 'Generar borradores, controlar versiones y asociar evidencias.'),
  ('FORM-POLITICA-SEGURIDAD', 'Politica Seguridad', 'politica_seguridad', 'liderazgo', '5.2', 'planear', '["id", "id_organizacion", "id_usuario", "contenido", "fecha_firma", "firma_imagen_url", "archivo_adjunto", "fecha_creacion", "fecha_actualizacion", "estado"]', '["organizaciones", "usuarios", "documentos", "evidencias"]', 'Registro diligenciado de Politica Seguridad', 'Preparar borradores para aprobacion de la direccion.'),
  ('FORM-ROLES-RESPONSABILIDADES', 'Roles Responsabilidades', 'roles_responsabilidades', 'personal', '5.3', 'planear', '["id", "id_organizacion", "id_usuario", "nombre_rol", "responsabilidades", "autoridad", "fecha_creacion", "fecha_actualizacion"]', '["organizaciones", "usuarios", "personas", "cargos"]', 'Registro diligenciado de Roles Responsabilidades', 'Detectar brechas de competencia, conciencia y asignacion.'),
  ('FORM-NORMOGRAMA', 'Normograma', 'normograma', 'legal', '6.1.3', 'planear', '["id", "id_organizacion", "id_usuario", "tipo_norma", "numero_norma", "titulo", "entidad_emisora", "fecha_emision", "fecha_vigencia", "aplicabilidad", "responsable_cumplimiento", "medio_verificacion", "estado_cumplimiento", "enlace_norma", "fecha_creacion", "fecha_actualizacion"]', '["organizaciones", "usuarios", "requisitos_normativos", "acciones_gestion"]', 'Registro diligenciado de Normograma', 'Alertar vencimientos y requisitos legales sin evidencia.'),
  ('FORM-POLITICA-SGS', 'Politica Sgs', 'politica_sgs', 'liderazgo', '5.2', 'planear', '["id", "id_organizacion", "id_usuario", "contenido", "fecha_firma", "archivo_adjunto", "fecha_creacion", "fecha_actualizacion", "estado"]', '["organizaciones", "usuarios", "objetivos_sgs", "documentos"]', 'Registro diligenciado de Politica Sgs', 'Preparar borradores para aprobacion de la direccion.'),
  ('FORM-OBJETIVOS-SGS', 'Objetivos Sgs', 'objetivos_sgs', 'objetivos', '6.2', 'planear', '["id", "id_politica", "objetivo", "indicador", "meta"]', '["politica_sgs", "plan_objetivos_sgs", "seguimiento_medicion"]', 'Registro diligenciado de Objetivos Sgs', 'Preparar planes, indicadores y seguimiento de objetivos.'),
  ('FORM-PLAN-OBJETIVOS-SGS', 'Plan Objetivos Sgs', 'plan_objetivos_sgs', 'objetivos', '6.2', 'planear', '["id", "id_objetivo", "que_se_hara", "recursos", "responsable", "cuando", "como_se_evaluara"]', '["objetivos_sgs", "acciones_gestion", "seguimiento_medicion"]', 'Registro diligenciado de Plan Objetivos Sgs', 'Preparar planes, indicadores y seguimiento de objetivos.'),
  ('FORM-CARGOS', 'Cargos', 'cargos', 'personal', '5.3', 'planear', '["id", "nombre", "descripcion", "fecha_creacion"]', '["personas", "competencias_minimas", "asignaciones_personal"]', 'Registro diligenciado de Cargos', 'Detectar brechas de competencia, conciencia y asignacion.'),
  ('FORM-COMPETENCIAS-MINIMAS', 'Competencias Minimas', 'competencias_minimas', 'personal', '7.2', 'hacer', '["id", "id_cargo", "competencia", "fuente_normativa", "observaciones"]', '["cargos", "evaluaciones_competencia", "certificados_competencia"]', 'Registro diligenciado de Competencias Minimas', 'Detectar brechas de competencia, conciencia y asignacion.'),
  ('FORM-PERSONAS', 'Personas', 'personas', 'personal', '7.2', 'hacer', '["id", "id_organizacion", "nombre_completo", "numero_identificacion", "tipo_identificacion", "telefono", "correo_electronico", "perfil_general", "fecha_creacion"]', '["organizaciones", "cargos", "asignaciones_personal", "capacitacion_asistentes", "certificados_competencia"]', 'Registro diligenciado de Personas', 'Detectar brechas de competencia, conciencia y asignacion.'),
  ('FORM-COMPROMISO-PERSONAL', 'Compromiso Personal', 'compromiso_personal', 'personal', '7.3', 'hacer', '["id", "id_persona", "id_organizacion", "cargo_funcion", "fecha_firma", "archivo_firma", "observaciones", "fecha_creacion"]', '["personas", "sistemas_gestion", "evidencias"]', 'Registro diligenciado de Compromiso Personal', 'Detectar brechas de competencia, conciencia y asignacion.'),
  ('FORM-PLAN-COMUNICACIONES', 'Plan Comunicaciones', 'plan_comunicaciones', 'comunicaciones', '7.4', 'hacer', '[]', '["organizaciones", "registro_comunicaciones_seguridad"]', 'Registro diligenciado de Plan Comunicaciones', 'Validar comunicaciones requeridas y evidencias.'),
  ('FORM-REGISTRO-COMUNICACIONES-SEGURIDAD', 'Registro Comunicaciones Seguridad', 'registro_comunicaciones_seguridad', 'comunicaciones', '7.4', 'hacer', '[]', '["organizaciones", "plan_comunicaciones", "evidencias"]', 'Registro diligenciado de Registro Comunicaciones Seguridad', 'Validar comunicaciones requeridas y evidencias.'),
  ('FORM-DOCUMENTOS-CONTROLADOS', 'Documentos Controlados', 'documentos_controlados', 'documentos', '7.5', 'hacer', '["id", "id_organizacion", "titulo", "codigo", "tipo_documento", "version", "fecha_emision", "autor", "formato", "medio", "ubicacion", "estado", "control_cambios", "origen", "acceso", "restricciones_acceso", "responsable_aprobacion", "fecha_aprobacion", "retencion_minima", "disposicion_final", "fecha_creacion_registro"]', '["organizaciones", "documentacion_minima", "documentos", "documento_versiones"]', 'Registro diligenciado de Documentos Controlados', 'Generar borradores, controlar versiones y asociar evidencias.'),
  ('FORM-DOCUMENTACION-MINIMA', 'Documentacion Minima', 'documentacion_minima', 'documentos', '7.5', 'hacer', '["id", "numeral_iso", "tipo", "descripcion", "obligatorio"]', '["documentos_controlados", "requisitos_normativos"]', 'Registro diligenciado de Documentacion Minima', 'Generar borradores, controlar versiones y asociar evidencias.'),
  ('FORM-POLITICA-DATOS-PERSONALES', 'Politica Datos Personales', 'politica_datos_personales', 'participantes', '7.4', 'hacer', '[]', '["organizaciones", "participantes_evidencia_externa"]', 'Registro diligenciado de Politica Datos Personales', 'Registrar soporte externo sin guardar datos sensibles.'),
  ('FORM-BITACORA-ACTIVIDADES', 'Bitacora Actividades', 'bitacora_actividades', 'actividades', '8.1', 'hacer', '[]', '["organizaciones", "actividades_servicios", "personas", "registro_participantes_evidencia"]', 'Registro diligenciado de Bitacora Actividades', 'Cruzar actividad, personal, equipos, riesgos y participantes.'),
  ('FORM-PROCEDIMIENTOS-SERVICIO', 'Procedimientos Servicio', 'procedimientos_servicio', 'actividades', '8.1', 'hacer', '[]', '["organizaciones", "actividades_servicios", "documentos"]', 'Registro diligenciado de Procedimientos Servicio', 'Cruzar actividad, personal, equipos, riesgos y participantes.'),
  ('FORM-EQUIPOS', 'Equipos', 'equipos', 'equipos', '7.1', 'hacer', '[]', '["organizaciones", "actividades_servicios", "personas", "inspecciones_equipos", "mantenimientos_equipos"]', 'Registro diligenciado de Equipos', 'Alertar inspecciones, mantenimientos y equipos no operativos.'),
  ('FORM-PLAN-EMERGENCIA', 'Plan Emergencia', 'plan_emergencia', 'emergencias', '8.2', 'hacer', '["id", "id_organizacion", "id_actividad", "ubicacion_operacion", "riesgos_emergencias", "consecuencias", "procedimientos", "roles_personal", "evacuacion_heridos", "personal_capacitado", "equipos_disponibles", "entidades_contacto", "gestion_datos_participantes", "proteccion_datos", "frecuencia_simulacros", "registro_simulacros", "comunicacion_participantes", "revision_mejora", "proxima_accion", "fecha_proxima_accion", "fecha_creacion"]', '["organizaciones", "actividades_servicios", "simulacros", "documentos"]', 'Registro diligenciado de Plan Emergencia', 'Preparar planes, simulacros y acciones derivadas.'),
  ('FORM-SIMULACROS', 'Simulacros', 'simulacros', 'emergencias', '8.2', 'hacer', '["id", "id_organizacion", "id_actividad", "id_plan_emergencia", "tipo_simulacro", "fecha_simulacro", "participantes", "descripcion", "resultados", "proxima_accion", "fecha_proxima_accion", "archivo_evidencia", "fecha_creacion"]', '["sistemas_gestion", "actividades_servicios", "plan_emergencia", "acciones_gestion"]', 'Registro diligenciado de Simulacros', 'Preparar planes, simulacros y acciones derivadas.'),
  ('FORM-SIMULACRO-EVIDENCIAS', 'Simulacro Evidencias', 'simulacro_evidencias', 'emergencias', '8.2', 'hacer', '["id", "id_simulacro", "tipo_archivo", "descripcion", "url_archivo", "fecha_subida"]', '["simulacros", "evidencias", "acciones_gestion"]', 'Registro diligenciado de Simulacro Evidencias', 'Preparar planes, simulacros y acciones derivadas.'),
  ('FORM-REGISTRO-PARTICIPANTES-EVIDENCIA', 'Registro Participantes Evidencia', 'registro_participantes_evidencia', 'participantes', '7.4', 'hacer', '["id", "id_bitacora", "tipo_evidencia", "descripcion", "url_evidencia", "fecha_creacion"]', '["bitacora_actividades", "actividades_servicios", "evidencias"]', 'Registro diligenciado de Registro Participantes Evidencia', 'Registrar soporte externo sin guardar datos sensibles.'),
  ('FORM-REGISTRO-INCIDENTES', 'Registro Incidentes', 'registro_incidentes', 'incidentes', '8.3', 'hacer', '["id", "id_organizacion", "id_actividad", "fecha_hora_incidente", "ubicacion", "personas_involucradas", "condiciones_ambientales", "equipo_asociado", "descripcion_incidente", "causas_probables", "respuesta_emergencia", "consecuencias", "medidas_correctivas", "fuente_informacion", "archivo_evidencia", "incorporado_mapa_riesgos", "proxima_accion", "fecha_proxima_accion", "fecha_registro"]', '["sistemas_gestion", "actividades_servicios", "equipos", "acciones_gestion", "evidencias"]', 'Registro diligenciado de Registro Incidentes', 'Crear acciones correctivas y actualizar riesgos.'),
  ('FORM-ACCIONES-SUGERIDAS', 'Acciones Sugeridas', 'acciones_sugeridas', 'mejora', '10.2', 'actuar', '["id", "id_incidente", "sugerencia", "fecha_sugerencia"]', '["acciones_gestion", "requisitos_normativos", "evidencias"]', 'Registro diligenciado de Acciones Sugeridas', 'Crear acciones, seguimientos y verificacion de eficacia.'),
  ('FORM-SEGUIMIENTO-MEDICION', 'Seguimiento Medicion', 'seguimiento_medicion', 'indicadores', '9.1', 'verificar', '["id", "id_organizacion", "id_actividad", "fecha_registro", "tipo_seguimiento", "indicador", "medicion", "observaciones", "acciones_a_tomar", "proxima_accion", "fecha_proxima_accion", "archivo_evidencia", "fecha_creacion"]', '["organizaciones", "actividades_servicios", "objetivos_sgs", "acciones_gestion"]', 'Registro diligenciado de Seguimiento Medicion', 'Consolidar mediciones para revision y mejora.'),
  ('FORM-PROGRAMA-AUDITORIAS', 'Programa Auditorias', 'programa_auditorias', 'auditorias', '9.2', 'verificar', '["id", "id_organizacion", "periodo", "proceso_auditar", "criterios_auditoria", "auditor_responsable", "alcance", "frecuencia", "observaciones", "fecha_planeada", "fecha_creacion"]', '["sistemas_gestion", "auditorias"]', 'Registro diligenciado de Programa Auditorias', 'Preparar programa, plan, hallazgos y acciones.'),
  ('FORM-PLAN-AUDITORIA', 'Plan Auditoria', 'plan_auditoria', 'auditorias', '9.2', 'verificar', '["id", "id_programa_auditoria", "fecha_auditoria", "dia", "hora_inicio", "hora_fin", "actividad", "lugar", "responsable_actividad", "observaciones", "fecha_creacion"]', '["programa_auditorias", "auditorias"]', 'Registro diligenciado de Plan Auditoria', 'Preparar programa, plan, hallazgos y acciones.'),
  ('FORM-INFORME-AUDITORIA-DETALLE', 'Informe Auditoria Detalle', 'informe_auditoria_detalle', 'auditorias', '9.2', 'verificar', '["id", "id_informe_auditoria", "numeral_norma", "requisito", "conforme", "evidencia"]', '["informe_auditoria", "hallazgos_auditoria", "acciones_gestion"]', 'Registro diligenciado de Informe Auditoria Detalle', 'Preparar programa, plan, hallazgos y acciones.'),
  ('FORM-REFERENCIA-NORMA-ISO21101', 'Referencia Norma Iso21101', 'referencia_norma_iso21101', 'norma', '4.4', 'planear', '["id", "capitulo", "numeral", "titulo", "requisito"]', '["normas", "norma_versiones", "requisitos_normativos"]', 'Registro diligenciado de Referencia Norma Iso21101', 'Conectar registros con requisitos normativos y PHVA.'),
  ('FORM-ACCIONES-CORRECTIVAS', 'Acciones Correctivas', 'acciones_correctivas', 'mejora', '10.1', 'actuar', '["id", "id_informe_auditoria", "origen", "descripcion_no_conformidad", "accion_propuesta", "responsable", "fecha_implementacion_esperada", "estado", "fecha_creacion"]', '["acciones_gestion", "seguimientos_acciones_gestion", "evidencias"]', 'Registro diligenciado de Acciones Correctivas', 'Crear acciones, seguimientos y verificacion de eficacia.'),
  ('FORM-INFORME-AUDITORIA', 'Informe Auditoria', 'informe_auditoria', 'auditorias', '9.2', 'verificar', '["id", "id_plan_auditoria", "auditor", "fecha_informe", "conclusiones", "recomendaciones", "archivo_soporte", "fecha_creacion"]', '["plan_auditoria", "auditorias", "hallazgos_auditoria"]', 'Registro diligenciado de Informe Auditoria', 'Preparar programa, plan, hallazgos y acciones.'),
  ('FORM-SEGUIMIENTO-ACCIONES-CORRECTIVAS', 'Seguimiento Acciones Correctivas', 'seguimiento_acciones_correctivas', 'mejora', '10.1', 'actuar', '["id", "id_accion_correctiva", "fecha_seguimiento", "descripcion_seguimiento", "estado_accion", "verificacion_eficacia", "usuario_seguimiento", "archivo_evidencia", "fecha_creacion"]', '["acciones_gestion", "seguimientos_acciones_gestion", "evidencias"]', 'Registro diligenciado de Seguimiento Acciones Correctivas', 'Crear acciones, seguimientos y verificacion de eficacia.'),
  ('FORM-REVISION-DIRECCION', 'Revision Direccion', 'revision_direccion', 'revision_direccion', '9.3', 'verificar', '["id", "id_organizacion", "fecha_revision", "estado_acciones_previas", "cambios_contexto", "resumen_no_conformidades", "resumen_medicion_seguimiento", "resumen_auditorias", "oportunidades_mejora", "decisiones_tomadas", "proxima_accion", "fecha_proxima_accion", "archivo_evidencia", "fecha_creacion"]', '["revisiones_direccion", "acciones_gestion", "auditorias", "incidentes", "capacitaciones"]', 'Registro diligenciado de Revision Direccion', 'Consolidar entradas y salidas para aprobacion directiva.'),
  ('FORM-PROCEDIMIENTOS-OBLIGATORIOS', 'Procedimientos Obligatorios', 'procedimientos_obligatorios', 'documentos', '4.4', 'planear', '["id", "codigo", "titulo", "numeral_iso", "descripcion", "obligatorio"]', '["procedimientos_sgs", "procedimientos_implementados", "requisitos_normativos"]', 'Registro diligenciado de Procedimientos Obligatorios', 'Generar borradores, controlar versiones y asociar evidencias.'),
  ('FORM-PROCEDIMIENTOS-IMPLEMENTADOS', 'Procedimientos Implementados', 'procedimientos_implementados', 'documentos', '8.1', 'hacer', '["id", "id_procedimiento_sgs", "id_procedimiento_obligatorio", "fecha_vinculacion", "cumple_requisitos", "comentarios"]', '["procedimientos_sgs", "procedimientos_obligatorios", "documentos", "evidencias"]', 'Registro diligenciado de Procedimientos Implementados', 'Generar borradores, controlar versiones y asociar evidencias.')
)
INSERT INTO formulario_tabla_matriz (
  codigo_formulario,
  nombre_formulario,
  tabla_principal,
  modulo,
  requisito_codigo,
  etapa_phva,
  campos,
  tablas_relacionadas,
  evidencia_generada,
  accion_agente
)
SELECT
  codigo_formulario,
  nombre_formulario,
  tabla_principal,
  modulo,
  requisito_codigo,
  etapa_phva::phva_etapa,
  campos::jsonb,
  tablas_relacionadas::jsonb,
  evidencia_generada,
  accion_agente
FROM matrix
ON CONFLICT (codigo_formulario) DO UPDATE
  SET nombre_formulario = EXCLUDED.nombre_formulario,
      tabla_principal = EXCLUDED.tabla_principal,
      modulo = EXCLUDED.modulo,
      requisito_codigo = EXCLUDED.requisito_codigo,
      etapa_phva = EXCLUDED.etapa_phva,
      campos = EXCLUDED.campos,
      tablas_relacionadas = EXCLUDED.tablas_relacionadas,
      evidencia_generada = EXCLUDED.evidencia_generada,
      accion_agente = EXCLUDED.accion_agente,
      activo = true;

CREATE INDEX IF NOT EXISTS idx_formulario_tabla_matriz_requisito ON formulario_tabla_matriz(requisito_codigo);
CREATE INDEX IF NOT EXISTS idx_formulario_tabla_matriz_modulo ON formulario_tabla_matriz(modulo);
CREATE INDEX IF NOT EXISTS idx_formulario_tabla_matriz_phva ON formulario_tabla_matriz(etapa_phva);
